### ISSUE TITLE
Отключение transition'а для box-shadow при фокусе на элементе

### ISSUE THREAD

**Issue by Turanchoks** [sberdevices/plasma#1049]
Иногда необходимо использовать навигацию в галереях без скрола. Сейчас в функцию addFocus вшит `transition: box-shadow 0.2s ease-in-out;`. Можем поддержать отключение анимации в addFocus на box shadow и, соответственно, добавить соответствующие пропсы в компоненты, которые используют addFocus? Спасибо

**Comment by Yeti-or** [comment]
Вопрос почему галлерея бес скролла предполагает отключение анимации на фокусное состояние?

**Comment by arsenykruglikov** [comment]
Есть запрос от пользователей и разрабов телеков Самсунг. `transition` рамки там выглядит как лаги и тормоза. Приходится выключать ручками в css

**Comment by fanisco** [comment]
Добавим возможность отключения. C миксином `addFocus` будет легко - добавим проп, с компонентами будет сложнее, но тоже осуществимо.

**Comment by arsenykruglikov** [comment]
Круто, а когда можно ждать? И позовите в ПР, когда он будет )
