### ISSUE TITLE
Card: добавить дефолтный placeholder в CardMedia

### ISSUE THREAD

**Issue by olga-venger** [sberdevices/plasma#154]
До загрузки целевого изображения или если не удастся загрузить изображение, отображать плейсхолдер, который можно прокинуть, например, как пропс placeholder.

**Comment by Yeti-or** [comment]
Я правильно понимаю хочется чего-то такого: https://codesandbox.io/s/plasma-cards-media-loading-75m9z?file=/src/App.js
