### ISSUE TITLE
ui: убрать выделение по долгому нажатию

### ISSUE THREAD

**Issue by Yeti-or** [sberdevices/plasma#204]
нужно в глобальные стили докидывать user-select:none
либо проставить что-то типа:  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);

иначе по долгому нажатию происходит бессмысленное выделение текста

**Comment by fanisco** [comment]
@Yeti-or Тут нужен список компонентов, в которых убираем выделение

**Comment by Yeti-or** [comment]
на всё что контролы я думаю
