### ISSUE TITLE
button: Добавить возможность использовать несколько строк в кнопке

### ISSUE THREAD

**Issue by Yeti-or** [sberdevices/plasma#228]

**Comment by Crusader727** [comment]
![image](https://user-images.githubusercontent.com/23740415/109268109-ac979f00-781b-11eb-846c-1f2c2a44665f.png)
тут просто стоит  -webkit-line-clamp: 2

**Comment by Yeti-or** [comment]
<img width="263" alt="Снимок экрана 2021-02-26 в 10 24 30" src="https://user-images.githubusercontent.com/1813468/109268921-d2717380-781c-11eb-977e-fcb4ad05d122.png">
в текущем виде мы никак не хендлим этот момент, надо поправить
