### ISSUE TITLE
Размер иконок в Stepper "пляшет" при импорте 

### ISSUE THREAD

**Issue by Igor3411** [sberdevices/plasma#231]
https://codesandbox.io/s/plasma-stepper-1mqjg?file=/src/App.js
https://ibb.co/QKVVyzZ
https://ibb.co/ftc9dpx

**Comment by fanisco** [comment]
@Igor3411 посмотри последнюю версию, мы тут явно указываем размер иконки в степпере. Обновил твой пример: https://codesandbox.io/s/plasma-stepper-forked-4xkux
