### ISSUE TITLE
Нельзя сослаться на props ratio у CardMediaProps

### ISSUE THREAD

**Issue by artra** [sberdevices/plasma#242]
CardMediaProps['ratio'];
// Property 'ratio' does not exist on type 'CardMediaProps'.  TS2339

"name": "@sberdevices/ui",
 "version": "1.0.0-rc.61",

**Comment by fanisco** [comment]
@artra Пример?

**Comment by artra** [comment]
да я просто пытался написать ts interface типа
```
interface props {
    ratio: CardMediaProps['ratio'];
}
```
и оно падает так

**Comment by fanisco** [comment]
Теперь можно писать
`export { Ratio } from '@sberdevices/plasma-ui/components/Image';`
https://github.com/sberdevices/plasma/blob/master/packages/plasma-ui/src/components/Image/Image.tsx#L22
