### ISSUE TITLE
Tabs: при touch-клике свечение

### ISSUE THREAD

**Issue by KIlyaA** [sberdevices/plasma#262]
![Запись-экрана-2021-03-24-в-18 10 14](https://user-images.githubusercontent.com/12472776/112334966-e483ec00-8ccc-11eb-921d-fe3282979511.gif)

**Comment by Yeti-or** [comment]
Это же тоже самое да ? 
https://github.com/sberdevices/plasma/issues/204

**Comment by KIlyaA** [comment]
> Это же тоже самое да ?
> #204

Не уверен что тоже самое, но #204 тоже нужно исправить
Кажется на это свечение влияет `cursor: pointer` у табов
