### ISSUE TITLE
Swtich: добавить тип "JSX.Element" для параметра "label"

### ISSUE THREAD

**Issue by stanislav-suslov** [sberdevices/plasma#421]
Добрый день!

Для компонента `<Switch />` в параметр `label` необходимо указывать текст с переносом строки. На данный момент следующий код работает корректно:
```tsx
<Switch
  label={
    <>
      First line
      <br />Second line
    </>
  }
/>
```

однако выдает ошибку о несовместимости типов — параметр `label` принимает только `string | number` ([ссылка на код](https://github.com/sberdevices/plasma/blob/4cbdb86bdbfae262846f9effeccf11ea0867c0d8/packages/plasma-core/src/components/Basebox/Basebox.tsx#L24)).

**Comment by fanisco** [comment]
Не уверен, что в `label` можно заносить верстку. @stanislav-suslov покажешь пример в дизайне (скриншотом)?

**Comment by fanisco** [comment]
@stanislav-suslov разметку добавлять в поле `label` нельзя потому что:

1. `label` - строчный элемент, должен подчиняться всем правилам inline-потока
2. добавление разметки приведет к нецелевому использованию поля (произвольная разметка с произвольными стилями)
