### ISSUE TITLE
Add TextArea component

### ISSUE THREAD

**Issue by MishaKazakov** [sberdevices/plasma#433]
Хочется, чтобы TextField расширялся при появлении новых строк как textarea

**Comment by fanisco** [comment]
@MishaKazakov какой пакет компонентов используется: `plasma-ui` или `plasma-web`?

**Comment by MishaKazakov** [comment]
plasma-ui

**Comment by fanisco** [comment]
@MishaKazakov для этого надо использовать компонент TextArea, задача в работе.
