### ISSUE TITLE
[Toast] При position: 'top' оверлэй все равно снизу

### ISSUE THREAD

**Issue by MishaKazakov** [sberdevices/plasma#495]
```
showToast('someText', 'top', undefined, true);
```

https://user-images.githubusercontent.com/33093997/124304812-ed5a4880-db6c-11eb-8398-9f0e35ccd5e2.mov

**Comment by kplv** [comment]
@fanisco привет! а можешь плиз поменять цвет тоста на background-01, чтобы было как в дизайн-системе. А то чёрный на чёрном сливается. backrground 01 — это #171717
