### ISSUE TITLE
Описать смену персонажа внутри canvas апп

### ISSUE THREAD

**Issue by Yeti-or** [sberdevices/plasma#55]
В документации должен быть хороший пример про взаимодействие между assistant-client и смену темы их `plasma-tokens`

Нужно показать вариант как можно догружать тему лениво

**Comment by snyuryev** [comment]
не подойдет? уже начал у себя делать такую функциональность
https://gist.github.com/snyuryev/55c2d1d5072529bffd43c5913123ae64#file-react-change-theme

**Comment by Yeti-or** [comment]
Это прям оно

**Comment by Yeti-or** [comment]
@snyuryev может закинишь нам этот пример в `./packages/ui/src/components/theme.mdx`, а мы доведем до красоты?
по примеру https://github.com/sberdevices/plasma/blob/rc/packages/ui/src/components/pallete.mdx

**Comment by snyuryev** [comment]
@Yeti-or ок
