### ISSUE TITLE
spread operator in es build of plasma-ui

### ISSUE THREAD

**Issue by fenderil** [sberdevices/plasma#594]
В компоненте ActionButton присутствует spread оператор (props spreading). При генерации es сборки plasma-ui этот оператор не подвергается преобразованию babel'ем. В итоге в IE падает ошибка неподдерживаемого синтаксиса.

Данную проблему можно решить добавлением пресета @babel/preset-env в плагин babel конфигурации rollup. Иначе можно более точечно решить проблему, включив @babel/plugin-proposal-object-rest-spread. Я бы рекомендовал именно preset, поскольку неизвестно, из-за какого еще синтаксиса сборка может быть в последующем неполноценно переведена в es5.

**Comment by fanisco** [comment]
@fenderil Какая версия пакета?

**Comment by fenderil** [comment]
1.24.0, 1.31.1 и проверил в master ветке

**Comment by fanisco** [comment]
@fenderil в версии `1.32.0` внесли исправления в билд пакетов, так что установка последней версии должна помочь, там объект спредит babel-helper
`npm i @sberdevcies/plasma-ui@latest`
