### ISSUE TITLE
Описать детектирование устройства внутри canvas-app

### ISSUE THREAD

**Issue by Yeti-or** [sberdevices/plasma#83]
Сейчас в plasma/ui есть хелперы для детектирования девайса:
```
import { detectDevice } from '@sberdevices/ui/utils';
```

нужно докинуть в документацию их использование и скинуть эту доку вот в этот тикет: 
https://github.com/sberdevices/salute-issues/issues/60

**Comment by snyuryev** [comment]
@Yeti-or пример есть. что скажете?
https://gist.github.com/snyuryev/6b6bb391f541c94248ec760a936cd1c3

**Comment by Yeti-or** [comment]
сорри переназывали задачку и забыли закрыть:
https://plasma-docs.netlify.app/utils#detectdevice

https://github.com/sberdevices/plasma/pull/88

**Comment by Yeti-or** [comment]
хотя у вас пример побогаче конечно стоит это добавить в доку

**Comment by snyuryev** [comment]
глянул в доку

// Вернет "SberPortal" или "SberBox" или "touch" (для всех остальных устройств)

но ведь там "sberPortal", "sberBox"
