### ISSUE TITLE
Нету папки helpers

### ISSUE THREAD

**Issue by vitmih** [sberdevices/plasma#89]
При установке @sberdevices/ui@rc не подтягивается папка helpers. Так и должно быть? Тогда примеры не работают

**Comment by Yeti-or** [comment]
@vitmih покажи пожалуйста какой пример не работает

**Comment by vitmih** [comment]
Например компонент Card. Там есть к  <IconPlaceholder size={2.25} />. Или ImagePlaceholder. Они, вроде, импортируются у вас из helpers.
import { ThemeSelect } from '../../helpers/ThemeSelect'
 import { ThemeBackground } from '../../helpers/ThemeBackground'
 import { IconPlaceholder } from '../../helpers/IconPlaceholder'
 import { ImagePlaceholder } from '../../helpers/ImagePlaceholder'

**Comment by fanisco** [comment]
@vitmih наверняка вы пытаетесь использовать компоненты неправильно: в файле компонента Card (https://github.com/sberdevices/plasma/blob/rc/packages/ui/src/components/Card/Card.tsx) нет обозначенных вами хелперов, все хелперы доступны для использования **только внутри Storybook** (например тут: https://github.com/sberdevices/plasma/blob/rc/packages/ui/src/components/Card/Card.stories.tsx).
Для того, чтобы открыть Storybook, пройдите по ссылке соответствующей ссылке https://rc--5f96ec813d800900227e3b93.chromatic.com/ (на данный момент для ветки _rc_).
Для того, чтобы открыть Storybook у себя локально, склонируйте данный репозиторий к себе на компьютер, затем проведите установку пакета ui (cd packages/ui && npm i) и запустите Storybook (npm run storybook).

**Comment by vitmih** [comment]
Поэтому я и спросил "Так и должно быть?" Просто вижу, на гитхабе есть helpers, и нигде не указано, что они не для использования в компонентах, а только для сторибука. Спасибо за разъяснение.
