### ISSUE TITLE
Компонент Image в @sberdevices/plasma-ui@1.58.3+ работает неправильно

### ISSUE THREAD

**Issue by sir-rois** [sberdevices/plasma#907]
**Компонент Image отображается неверно**
![image](https://user-images.githubusercontent.com/3797524/139746274-bf5f3b2a-f69d-4447-8d4d-71cf8f1af2f0.png)

**Версия пакета**
`@sberdevices/plasma-ui@1.58.3` и выше

**Возвращаем следующий код в render() страницы**
```
<Container>
  <Row>
    <Col>
      <TextBox title='Image test' />
    </Col>
  </Row>
  <Row>
    <Col>
      <Image src={'https://cdn-app.sberdevices.ru/misc/0.0.0/test/sbol_icon_7d806930fc.png'} />
    </Col>
  </Row>
</Container>
```

**Ожидаемое отображение**
![image](https://user-images.githubusercontent.com/3797524/139746499-6b43b577-fe1c-4857-951f-f573a14da924.png)
это работает в версии `@sberdevices/plasma-ui@1.58.2`

**Comment by fanisco** [comment]
@sir-rois на компоненте `Image` нужно будет указывать пропы `width` и `height`, после применения фикса.
