### ISSUE TITLE
Carousel: добавить пример в документацию

### ISSUE THREAD

**Issue by Yeti-or** [sberdevices/plasma#91]

**Comment by vitmih** [comment]
речь про Сarousel?

**Comment by snyuryev** [comment]
@Yeti-or я сделал у себя пример (на основе карусели из сториборда) с карточками (+ привязку к клавиатуре, что бы можно было пультом ходить по карточкам)

https://github.com/s41ty/sber-react-demo/blob/main/src/MarketPage.tsx

**Comment by snyuryev** [comment]
правда не уверен за кнопку ОК на пульте

**Comment by snyuryev** [comment]
может быть даже есть смысл добавить в хелперы (в plasma или сдк)
https://github.com/s41ty/sber-react-demo/blob/main/src/useKeyboard.tsx

т.к. спрашивали уже про события с пульта
https://github.com/sberdevices/salute-issues/issues/34
